launchdarkly/go-client

ldclient.go
requestor.go
streaming.go

Supports large feature patches by accepting indirect events, which are pointers to the feature flag to be updated

Support for indirect patch events

---

events.go
ldclient.go

Add a sampling interval to allow clients to send a sampled subset

---

flag.go

Prerequisites are not hooked into the evaluation algorithm yet.

Add prerequisites to the data model

---

flag.go
ldclient.go
sdk_test.go
testdata/sdk_test_data.json

[wip] Add prereq support.. see TODOs for open questions.

[wip] Add prereq support

---

polling.go
requestor.go
streaming.go

Also added some reuse in the requestor + added some log statements when the client is starting up.

Use new SDK endpoint.

---

ldclient.go

New method that returns all feature flags for a given user

AllFlags method for go client

---

events.go

see https://github.com/golang/go/issues/3611

Use the global rand instead of our own

---

test_harness/reps.go

Add field to test harness rep for use in integration-harness and restwrapper.

Add type field to test harness rep

---

requestor.go

Constructing the flags resource requires no state

---

streaming.go

Send signal on channel when starting with a put/indirect event.

Send signal on channel when starting with a put/indirect event.

---

operators.go

Also make available a function that returns each operator's name

Make a list of all operators available. 

---

flag.go

It seemed a bit unnecessary to both pass the events and visited map as parameters and return them, given that we were mutating them.

Clean up prerequisite evaluation

---

events.go
feature_store.go
flag.go
ldclient.go
ldclient_test.go
polling.go
redis/redis.go
requestor.go
util.go

See green items here: https://catamorphic.quip.com/Ggk6AbylpJBf for details on what is included.

[HOLD} Some final polish before releasing v2.

---

ldclient.go

This passes the v2 integration harness

Now Check for offVariation in allFlags

---

redis.go

Fix redis All() function

---

ldclient.go

Allow empty string as user key in flag eval

Allow empty string as user key in flag eval

---

redis.go

Better redis delete behavior

---

redis.go

see writeup: https://catamorphic.quip.com/dah4AU3Xkoas

RedisFeatureStore: enable local cache for All()

---

redis/redis.go

I tested this locally on v1 restwrapper- all evaluation assertions passed.

Backport RedisFeatureStore improvements

---

redis.go

Improve in-memory caching in redis feature store

Improve in-memory caching in redis feature store

---

README.md

FYI the pages on the [Launch Darkly site](http://docs.launchdarkly.com/v2.0/docs/getting-started) are out of date too

Updating docs for Toggle function
